AWSTemplateFormatVersion: '2010-09-09'
Description: Shared Application Load Balancer for multi-customer deployment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  AppName:
    Type: String
    Default: task-manager
    Description: Application name

  WildcardCertificateArn:
    Type: String
    Description: ARN of wildcard SSL certificate (*.freeinterestcal.com)

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${Environment}-${AppName}-shared-alb'
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - Fn::ImportValue: !Sub '${Environment}-public-subnet-1-id'
        - Fn::ImportValue: !Sub '${Environment}-public-subnet-2-id'
      SecurityGroups:
        - Fn::ImportValue: !Sub '${Environment}-${AppName}-alb-sg-id'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-shared-alb'
        - Key: Environment
          Value: !Ref Environment

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${Environment}-${AppName}-default-tg'
      Port: 80
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub '${Environment}-vpc-id'
      TargetType: ip
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-default-tg'

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref WildcardCertificateArn
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: 'Instance not found. Please check your URL.'

Outputs:
  LoadBalancerArn:
    Description: ARN of the shared Application Load Balancer
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub '${Environment}-${AppName}-shared-alb-arn'

  LoadBalancerDNS:
    Description: DNS name of the shared Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${Environment}-${AppName}-shared-alb-dns'

  LoadBalancerHostedZoneId:
    Description: Canonical hosted zone ID of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub '${Environment}-${AppName}-shared-alb-hosted-zone-id'

  HTTPSListenerArn:
    Description: ARN of the HTTPS Listener
    Value: !Ref HTTPSListener
    Export:
      Name: !Sub '${Environment}-${AppName}-https-listener-arn'

