AWSTemplateFormatVersion: '2010-09-09'
Description: Shared IAM Roles for all customers

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  AppName:
    Type: String
    Default: task-manager
    Description: Application name

Resources:
  # Shared Task Execution Role (used by ECS to pull images and write logs)
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${AppName}-task-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECRAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/*'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-task-execution-role'
        - Key: Environment
          Value: !Ref Environment

  # Shared Task Role (used by the application at runtime)
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${AppName}-task-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-task-role'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  TaskExecutionRoleArn:
    Description: ARN of the shared task execution role
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: !Sub '${Environment}-${AppName}-task-execution-role-arn'

  TaskRoleArn:
    Description: ARN of the shared task role
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: !Sub '${Environment}-${AppName}-task-role-arn'

